/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "active-races": { "allowsEmptySelection": true, "dataArray": ["Race 1", "Race 2", "Race 3"], "labelElementId": "label", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3, "selectionEnabled": true, "view": "DC.List" },
    "add-date": { "initialHeight": 30, "initialWidth": 104, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Add Points", "view": "DC.PushButton" },
    "add-items": { "initialHeight": 30, "initialWidth": 100, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Add Items", "view": "DC.PushButton" },
    "application-layout": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "back-button": { "initialHeight": 30, "initialWidth": 70, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back", "view": "DC.PushButton" },
    "button": { "initialHeight": 30, "initialWidth": 302, "leftImageWidth": 5, "onclick": "newracebuttonhandler", "rightImageWidth": 5, "text": "New Race", "view": "DC.PushButton" },
    "button1": { "initialHeight": 30, "initialWidth": 240, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Tweet", "view": "DC.PushButton" },
    "checkin-button": { "initialHeight": 30, "initialWidth": 277, "leftImageWidth": 5, "onclick": "checkinbuttonhandler", "rightImageWidth": 5, "text": "Checkin", "view": "DC.PushButton" },
    "create-button": { "initialHeight": 30, "initialWidth": 297, "leftImageWidth": 5, "onclick": "creaeracehandler", "rightImageWidth": 5, "text": "Create Race", "view": "DC.PushButton" },
    "distance-text": { "text": "Distance to destination: 10km", "view": "DC.Text" },
    "fead-header": { "text": "Live Tweets", "view": "DC.Text" },
    "footer": { "text": "CPSC 410", "view": "DC.Text" },
    "header": { "rootTitle": "MappedRacer", "view": "DC.Header" },
    "image": { "view": "DC.ImageLayout" },
    "image1": { "view": "DC.ImageLayout" },
    "image2": { "view": "DC.ImageLayout" },
    "image3": { "view": "DC.ImageLayout" },
    "label": { "text": "Race", "view": "DC.Text" },
    "logout-text": { "text": "Logout", "view": "DC.Text" },
    "main-browser": { "clearSelectionOnBack": true, "view": "DC.Browser" },
    "map-image": { "view": "DC.ImageLayout" },
    "map-image1": { "view": "DC.ImageLayout" },
    "name": { "text": "@igman05", "view": "DC.Text" },
    "profile-pic": { "view": "DC.ImageLayout" },
    "send-checkin-button": { "initialHeight": 30, "initialWidth": 308, "leftImageWidth": 5, "onclick": "sendcheckinhandler", "rightImageWidth": 5, "text": "Checkin", "view": "DC.PushButton" },
    "stackLayout": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "text": { "text": "@Igman05", "view": "DC.Text" },
    "text1": { "text": " I'm about to beat you all in a race!", "view": "DC.Text" },
    "text2": { "text": "450", "view": "DC.Text" },
    "text3": { "text": "@Homer", "view": "DC.Text" },
    "text4": { "text": "300", "view": "DC.Text" },
    "text5": { "text": "Add photo", "view": "DC.Text" },
    "tweet-header": { "text": "Send Tweet", "view": "DC.Text" },
    "twitter-login": { "view": "DC.ImageLayout" },
    "welcome-text": { "text": "Welcome to MappedRacer!", "view": "DC.Text" }
};

