/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "add-waypoint": { "text": "Add Waypoint:", "view": "DC.Text" },
    "button": { "initialHeight": 31, "initialWidth": 150, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Checkin", "view": "DC.PushButton" },
    "button3": { "initialHeight": 56, "initialWidth": 300, "leftImageWidth": 5, "onclick": "createbtnOnClickHandler", "rightImageWidth": 5, "text": "Create Race", "view": "DC.PushButton" },
    "create-race": { "text": "Create Race", "view": "DC.Text" },
    "destination": { "text": "Destination:", "view": "DC.Text" },
    "distance-text": { "text": "Distance to destination: 10 km", "view": "DC.Text" },
    "footer": { "text": "CPSC 410", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "image1": { "view": "DC.ImageLayout" },
    "image2": { "view": "DC.ImageLayout" },
    "invite-friend": { "text": "Invite Friend:", "view": "DC.Text" },
    "login-btn": { "view": "DC.ImageLayout" },
    "logo-text": { "text": "MappedRacer Logo", "view": "DC.Text" },
    "stackLayout": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "text": { "text": "@Igman05", "view": "DC.Text" },
    "text1": { "text": "Latest Tweets", "view": "DC.Text" },
    "text2": { "text": "This Race is really awesome! #mappedracer", "view": "DC.Text" },
    "text3": { "text": "Start Time:", "view": "DC.Text" }
};


